### ISSUE TITLE
Planning Regions (i.e. children of Johannesburg, Ekurhuleni, and Tswane) are not showing in GCRO, this needs to be debugged.

### ISSUE THREAD

**Issue by milafrerichs** [OpenUpSA/wazimap-ng-ui#114]
https://trello.com/c/Q8ZcZnrk/542-planning-regions-ie-children-of-johannesburg-ekurhuleni-and-tswane-are-not-showing-in-gcro-this-needs-to-be-debugged

**Comment by emre2038** [comment]
This issue was already fixed with the PR below

https://github.com/OpenUpSA/wazimap-ng-ui/pull/101
