### ISSUE TITLE
Fix: logo dimensions

### ISSUE THREAD

**Issue by milafrerichs** [OpenUpSA/wazimap-ng-ui#118]
the logo from GCRO is stretched. probably the height is the problem. 
please investigate and fix. maybe this is a css issue maybe not. 

https://trello.com/c/5t4CxNbo/535-fixed-logo-dimensions-currently-the-height-is-fixed-which-distorts-the-proportions

**Comment by milafrerichs** [comment]
the logo should be displayed in a nice way no matter at which size the image was uploaded.

**Comment by emre2038** [comment]
at the moment css for `.profile-logo` is

```
.profile-logo {
    height: 100%;
}
```
modifying it as
```
.profile-logo {
    margin: auto;
}
```
fixes the issue
