### ISSUE TITLE
Number formatting not applied to choropleth info window

### ISSUE THREAD

**Issue by milafrerichs** [OpenUpSA/wazimap-ng-ui#143]
1. Navigate to beta.youthexplorer.org.za
2. Open the data mapper
3. Select Youth poverty -> Multidimensional poverty -> Non poor
4. Hover over one of the geographies - you will see decimal points. When you compare with the corresponding graph in the rich data view, you will notice that formatting is applied there

**Comment by RomanMelnyk113** [comment]
Actually, the reason why we have different formatting in these 2 places is that it uses different logic in the code. 
1. For the popup window, it uses default formatting for Profile passed from API request
![image](https://user-images.githubusercontent.com/19851923/99734543-df165b00-2aba-11eb-827e-19e17272605c.png)
2. For the graph it uses formatting defined in `char_configuration`
![image](https://user-images.githubusercontent.com/19851923/99735806-2ef62180-2abd-11eb-9d9f-54a155e9ab7d.png)

So the question here should we use the same formatting from `char_configuration` for popup window as well? or simply use `.0f` for numbers in popup? @milafrerichs

**Comment by milafrerichs** [comment]
thanks for pointing that out. I'll have a look and report back.
