### ISSUE TITLE
Change order of values in chart download

### ISSUE THREAD

**Issue by milafrerichs** [OpenUpSA/wazimap-ng-ui#157]
As a User I donwload the data from a chart as csv or excel. 
I expect the data to be in the same order as on the chart.

the display on the screen
<img width="859" alt="Bildschirmfoto 2020-12-09 um 10 31 27" src="https://user-images.githubusercontent.com/688980/101611437-cccc7480-3a09-11eb-9cb3-3dabe96290f2.png">

the downloaded data:
Sub-indicator | Value
-- | --
45-54 | 5 %
36-44 | 7 %
30-35 | 20 %
25-29 | 21 %
20-24 | 9 %
15-19 | 9 %
5-9 | 9 %
0-4 | 10 %
10-14 | 9 %

**Comment by emre2038** [comment]
@milafrerichs can you give more details please

**Comment by milafrerichs** [comment]
@emre2038 updated the issue
