### ISSUE TITLE
Numbers of bar graphs are cut off on chart download

### ISSUE THREAD

**Issue by milafrerichs** [OpenUpSA/wazimap-ng-ui#173]
When I download a chart the numbers on the right side are cut off.

**Comment by emre2038** [comment]
@milafrerichs here is how it looks when I export an image. It looks fine to me, what is the issue exactly?

![image](https://user-images.githubusercontent.com/53019884/101287379-01b9ab00-3801-11eb-89db-c7477997fd27.png)

**Comment by milafrerichs** [comment]
switch to absolute values and you can see it:

![chart (1)](https://user-images.githubusercontent.com/688980/101320412-01063080-3864-11eb-8aae-52f269134353.png)
