### ISSUE TITLE
Change lorem ipsum on the first page of the tutorial box

### ISSUE THREAD

**Issue by adieyal** [OpenUpSA/wazimap-ng-ui#188]
This website was developed to enable you to easily find spatial information related to geographic areas. By clicking on the map or using the search bar, you can navigate to an area of interest and find relevant information about it.

Rel 0.11

https://trello.com/c/f48vPPkS/541-change-lorem-ipsum-on-the-first-page-of-the-tutorial-box

**Comment by milafrerichs** [comment]
fixed in #200
