### ISSUE TITLE
Data mapper shows sub-indicators in the data mapper, even when no data is available.

### ISSUE THREAD

**Issue by adieyal** [OpenUpSA/wazimap-ng-ui#216]
1. https://production.wazimap-ng.openup.org.za/api/v1/all_details/profile/8/geography/166008/?format=json
2. Notice that there isn't any children data under the Progress through school indicator. These options should not be visible.

I think that subindicators should not be visible if no data is available. If no data is available for any subindicators, then perhaps the entire indicator should not be available. Another approach would be to disable the link with a hover action the informs the user that no data is available for this geography

V 1.0

https://trello.com/c/S6C19eFQ/622-data-mapper-shows-sub-indicators-in-the-data-mapper-even-when-no-data-is-available

**Comment by emre2038** [comment]
hey @adieyal not sure if I'm missing something or has the API data been updated after you created this issue but data for that indicator looks correct to me. is there an example that I can examine? @milafrerichs FYI
![image](https://user-images.githubusercontent.com/53019884/105699341-3cde7d80-5f18-11eb-8459-a4777bd485a3.png)

**Comment by milafrerichs** [comment]
here is another example that illustrates the point a bit more:

<img width="923" alt="Bildschirmfoto 2021-03-10 um 13 23 14" src="https://user-images.githubusercontent.com/688980/110628880-d5b51980-81a3-11eb-8a34-40d98b71e6c8.png">

https://production.wazimap-ng.openup.org.za/api/v1/all_details/profile/20/geography/SOM/?format=json
<img width="466" alt="Bildschirmfoto 2021-03-10 um 13 26 32" src="https://user-images.githubusercontent.com/688980/110629253-41978200-81a4-11eb-8179-86c3705dd996.png">

there is no data for damns or water management, so these two should not show at all. 
and if the whole indicator has no data, do not show it at all.
