### ISSUE TITLE
Empty charts displaying where a variable is available for the children of the current geography but not the geography itself.

### ISSUE THREAD

**Issue by adieyal** [OpenUpSA/wazimap-ng-ui#226]
If we only have **Medical Aid** for provinces but not for the country then it will show as an empty chart in the country profile. The server sends the data without a count value but dataobjects sets that value to MISSING which is currently 0, hence the empty graph.

Not certain what the best solution is here.

0.13

https://trello.com/c/DjBREnu0/552-empty-charts-displaying-where-a-variable-is-available-for-the-children-of-the-current-geography-but-not-the-geography-itself

**Comment by emre2038** [comment]
Hey Adi, why not just hide the chart if all the values are 0?

**Comment by adieyal** [comment]
happy to hide it if that's easiest

**Comment by emre2038** [comment]
The charts are re-created everytime user navigates to a new geography so just hiding a chart if all the values are 0 seems the easiest. when user navigates to another geography that chart will be re-created with the new values anyway

**Comment by adieyal** [comment]
Is there an easy way to test this?
