### ISSUE TITLE
Make Facilities and Point configurable

### ISSUE THREAD

**Issue by adieyal** [OpenUpSA/wazimap-ng-ui#237]
We need to make this configurable as each instance may want its own language

https://trello.com/c/lrUPdcQW/646-change-facility-text-to-services

**Comment by milafrerichs** [comment]
We assume for now the BE returns a list of configurable text objects.

Let's call it `i18n` for now. 
It's kind off a translation. Maybe we use a translation library? 

For YE we want to change `Locations ` into `Service Areas`
and at some point we want "normal" translations. so let's treat this as a translation.

**Comment by adieyal** [comment]
sounds good to me
