### ISSUE TITLE
chart data downloads need to include all the raw data (filters/groups as well as absolute values) [4 hours]

### ISSUE THREAD

**Issue by adieyal** [OpenUpSA/wazimap-ng-ui#306]
0.14

https://trello.com/c/SCzSxrEO/385-chart-data-downloads-need-to-include-all-the-raw-data-filters-groups-as-well-as-absolute-values-4-hours

**Comment by Geeker1** [comment]
Hi @milafrerichs , I need more clarification on this task, a bit confused on where exactly to start.
