### ISSUE TITLE
Add tooltips back for Vega. 

### ISSUE THREAD

**Issue by milafrerichs** [OpenUpSA/wazimap-ng-ui#351]
Add tooltips back for Vega and make sure they have the format that is outlined in the designs.

The name of the hovered indicator should be shown as well as percentage and absolute value.

https://wazimap-ng.webflow.io/feature-previews/additive-filters-05212021

![Bildschirmfoto 2021-05-24 um 10 03 59](https://user-images.githubusercontent.com/688980/119316671-85fccf00-bc77-11eb-9898-be613cd723e9.png)

**Comment by milafrerichs** [comment]
best to use
https://github.com/vega/vega-tooltip
and https://github.com/vega/vega-tooltip/blob/master/docs/APIs.md#sanitize to create our own custom HTML.

**Comment by waracci** [comment]
Pr merged https://github.com/OpenUpSA/wazimap-ng-ui/pull/354
